version: '3.8'

services:
  app:
    build: .
    container_name: challenge-api
    command: 'sh -c "npm run migrate && npm start"'
    ports: 
      - 80:80
    volumes: 
      - ./:/app
    links:
      - db
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: postgres
  db:
    image: postgres:13
    container_name: 'db'
    volumes:
      - ./db/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres